'''
Created on 15 oct. 2019

@author: Val
'''

RESEARCH_LOG = "pyGenealogicalTools"
RESEARCH_INFO = "Research Log automatically generated by pyGenealogicalTools as tracking and storing of obtained results of automatic search"

MATCH_PROFILE_ERROR = "Profile provided does not contain the information of the GENI link"
MATCH_GENI = "This match was found automatically by PyGenealogical tools. MATCHED ON="
MATCH_CONFLICT_TASK = "CHECK GENI MATCH"
MATCH_CONFLICT_INFO = "This profile does not match with the following geni profile, when should == "